Diversity text added.
scipy-latinamerica/scipyla2017-web pull request #10
Opened 2017-07-19 20:11 UTC by xmnlab

PS: @olemis nos falta traducir el texto para español .. en inglés y portugués ya está listo. Estoy revisando este tema con Juanlu, y si realmente no tenemos el texto .. voy a anunciar en los grupos solicitando ayuda :)

2017-07-20 17:21 UTC, olemis requested changes
Everything ok . Spanish version missing ... but I know you're working on it .

Thanks !

2017-07-20 17:22 UTC, olemis commented
yo voy a ver si tengo un tiempo para subir todos los .md a Transifex

2017-07-20 18:27 UTC, xmnlab commented
Bacán !

2017-08-17 20:41 UTC, xmnlab commented
@olemis texto en español agregado (79a8800)

2017-08-18 16:10 UTC, merged